name: kitty_app
description: Expense Management android app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  google_fonts: ^3.0.1
  freezed: ^2.3.2
  flutter:
    sdk: flutter


  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  pdf: ^3.8.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  bloc: ^8.1.0
  json_serializable: ^6.5.4
  flutter_svg: ^1.1.6
  flutter_screen_lock: ^9.0.0+1
  equatable: ^2.0.5
  flutter_gen: ^5.1.0+1
  flutter_bloc: ^8.1.1
  easy_localization: ^3.0.1
  sqflite: ^2.2.2
  path: ^1.8.2
  open_filex: ^4.3.2
  image_picker: ^0.8.6+1
  flutter_secure_storage: ^7.0.1
  local_auth: ^2.1.3
  uuid: ^3.0.7
  smart_snackbars: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/categories/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
